apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: pg-restored
spec:
  instances: 1
  storage:
    size: 2Gi
  bootstrap:
    recovery:
      source: origin
      recoveryTarget:
        targetTime: "2026-10-04 14:32:24+00"
  externalClusters:
  - name: origin
    plugin:
      name: barman-cloud.cloudnative-pg.io
      parameters:
        barmanObjectName: aws-s3-store
        serverName: pg-cluster
